// Premium "Irish Safety" Palette - Cinematic Redesign
const palette = {
  emerald: {
    900: '#022c22',
    800: '#064e3b',
    700: '#047857',
    600: '#059669',
    500: '#10b981', // Main Emerald
    400: '#34d399',
  },
  slate: {
    950: '#020617', // Extreme Dark Background
    900: '#0f172a', // Surface Dark
    800: '#1e293b', // Elevated Surface
    700: '#334155',
    600: '#475569',
    500: '#64748b',
    400: '#94a3b8', // Muted Text
    300: '#cbd5e1',
    200: '#e2e8f0',
    100: '#f1f5f9',
    50: '#f8fafc',
  },
  crimson: {
    600: '#dc2626',
    500: '#ef4444', // Action Red
    400: '#f87171',
    transparent: 'rgba(239, 68, 68, 0.4)',
  },
  gold: {
    600: '#d97706',
    500: '#f59e0b',
    400: '#fbbf24', // Accent Gold
  },
  white: '#ffffff',
  black: '#000000',
  glass: 'rgba(15, 23, 42, 0.7)', // Frosted dark
  glassLight: 'rgba(255, 255, 255, 0.1)',
};

export const theme = {
  colors: {
    primary: palette.emerald[500],
    secondary: palette.slate[800],
    background: palette.slate[950],
    surface: palette.slate[900],
    text: palette.white,
    textSecondary: palette.slate[400],
    textLight: palette.white,
    accent: palette.gold[400],
    danger: palette.crimson[500],
    error: palette.crimson[500],
    success: palette.emerald[500],
    warning: palette.gold[500],
    info: palette.slate[400],
    border: palette.slate[800],
    sos: palette.crimson[500],
    overlay: 'rgba(2, 6, 23, 0.85)',
    gardaBlue: '#1d4ed8',
    glass: palette.glass,
    glassLight: palette.glassLight,
    emeraldGlass: 'rgba(16, 185, 129, 0.15)',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
    xxxl: 64,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
    full: 9999,
  },
  fonts: {
    size: {
      small: 12,
      medium: 16,
      large: 20,
      xl: 24,
      xlarge: 24,
      xxl: 32,
      xxlarge: 32,
      giant: 48,
    },
    weight: {
      regular: '400' as const,
      medium: '500' as const,
      bold: '700' as const,
      heavy: '900' as const,
    },
  },
  shadows: {
    small: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 3,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.4,
      shadowRadius: 12,
      elevation: 6,
    },
    large: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 16 },
      shadowOpacity: 0.6,
      shadowRadius: 24,
      elevation: 12,
    },
    glow: {
      shadowColor: palette.emerald[500],
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.6,
      shadowRadius: 20,
      elevation: 10,
    },
    sosGlow: {
      shadowColor: palette.crimson[500],
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.9,
      shadowRadius: 35,
      elevation: 20,
    },
  },
};

export type Language = 'en' | 'ga' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'pl' | 'ro' | 'nl';

export const translations = {
  en: {
    welcome: "Welcome to SLÁN",
    tagline: "Ireland's Advanced Safety Network",
    platformTitle: "Irish Citizen Safety Platform",
    welcomeSubtitle: "Welcome to the SLÁN Network",
    register: "Register",
    login: "Login",
    gardaLogin: "Garda Login",
    govLogin: "Government Login",
    officialLogin: "OFFICIAL LOGIN",
    username: "Username",
    password: "Password",
    createAccount: "Create Account",
    loginSubtitle: "Enter your username and password or use biometrics to login.",
    loginWithBiometrics: "Login with Biometrics",
    registerSubtitle: "Register your identity to join the Irish Citizen Safety Platform.",
    fullName: "Full Legal Name",
    identification: "Identification (PPSN)",
    parentDependentMode: "Child / Dependent Mode",
    sos: "SOS",
    safeWalk: "Safe Walk",
    crimeMap: "Crime Map",
    dvAlert: "Domestic Violence Alert",
    medicalProfile: "Medical Profile",
    report: "Report",
    settings: "Settings",
    emergencyActivated: "EMERGENCY ACTIVATED",
    gardaETA: "Garda ETA",
    cancelSOS: 'Cancel SOS',
    liveStatus: 'LIVE STATUS',
    guardians: "Guardians",
    feed: "News Hub",
  },
  ga: {
    welcome: 'Fáilte go SLÁN',
    tagline: 'Aon Tapáil. Abhaile Slán.',
    platformTitle: "Ardán Sábháilteachta Saoránach na hÉireann",
    welcomeSubtitle: "Fáilte chuig Líonra SLÁN",
    register: "Cláraigh",
    login: "Logáil Isteach",
    gardaLogin: "Logáil Isteach Gardaí",
    govLogin: "Logáil Isteach Rialtais",
    officialLogin: "LOGÁIL ISTEACH OIFIGIÚIL",
    username: "Ainm úsáideora",
    password: "Pasfhocal",
    createAccount: "Cruthaigh Cuntas",
    loginSubtitle: "Iontráil d'ainm úsáideora agus do phasfhocal nó bain úsáid as bithmhéadracht.",
    loginWithBiometrics: "Logáil Isteach le Bithmhéadracht",
    registerSubtitle: "Cláraigh d'aitheantas chun páirt a ghlacadh in Ardán Sábháilteachta Saoránach na hÉireann.",
    fullName: "Ainm Iomlán Dlíthiúil",
    identification: "Aitheantas (PPSN)",
    parentDependentMode: "Mód Leanaí / Cleithiúnaithe",
    sos: 'SOS',
    safeWalk: 'Siúlóid Shábháilte',
    crimeMap: 'Léarscáil Coireachta',
    dvAlert: 'Foláireamh DV',
    medicalProfile: 'Próifíl Leighis',
    report: 'Tuairisc',
    settings: 'Socruithe',
    emergencyActivated: 'ÉIGEANDÁIL GNÍOMHAITHE',
    gardaETA: 'Gardaí ar an mbealach',
    cancelSOS: 'Cealaigh SOS',
    liveStatus: 'STÁDAS BEO',
    guardians: "Caomhnóirí",
    feed: "Nuacht",
  },
  es: {
    welcome: "Bienvenido a SLÁN",
    tagline: "Red de Seguridad Avanzada de Irlanda",
    platformTitle: "Plataforma de Seguridad Ciudadana Irlandesa",
    welcomeSubtitle: "Bienvenido a la Red SLÁN",
    register: "Registrarse",
    login: "Iniciar Sesión",
    gardaLogin: "Inicio Garda",
    govLogin: "Inicio Gobierno",
    officialLogin: "INICIO OFICIAL",
    username: "Usuario",
    password: "Contraseña",
    createAccount: "Crear Cuenta",
    loginSubtitle: "Ingrese su usuario y contraseña o use biometría para iniciar sesión.",
    loginWithBiometrics: "Iniciar Sesión con Biometría",
    registerSubtitle: "Registre su identidad para unirse a la Plataforma de Seguridad Ciudadana Irlandesa.",
    fullName: "Nombre Legal Completo",
    identification: "Identificación (PPSN)",
    parentDependentMode: "Modo Niño / Dependiente",
    sos: "SOS",
    safeWalk: "Paseo Seguro",
    crimeMap: "Mapa de Crimen",
    dvAlert: "Alerta Violencia Doméstica",
    medicalProfile: "Perfil Médico",
    report: "Reportar",
    settings: "Ajustes",
    emergencyActivated: "EMERGENCIA ACTIVADA",
    gardaETA: "ETA de Garda",
    cancelSOS: 'Cancelar SOS',
    liveStatus: 'ESTADO EN VIVO',
    guardians: "Guardianes",
    feed: "Noticias",
  },
  fr: {
    welcome: "Bienvenue sur SLÁN",
    tagline: "Réseau de Sécurité Avancé d'Irlande",
    platformTitle: "Plateforme de Sécurité Citoyenne Irlandaise",
    welcomeSubtitle: "Bienvenue sur le Réseau SLÁN",
    register: "S'inscrire",
    login: "Connexion",
    gardaLogin: "Connexion Garda",
    govLogin: "Connexion Gouvernement",
    officialLogin: "CONNEXION OFFICIELLE",
    username: "Utilisateur",
    password: "Mot de passe",
    createAccount: "Créer un Compte",
    loginSubtitle: "Entrez votre nom d'utilisateur et votre mot de passe ou utilisez la biométrie.",
    loginWithBiometrics: "Connexion par Biométrie",
    registerSubtitle: "Enregistrez votre identité pour rejoindre la plateforme de sécurité citoyenne irlandaise.",
    fullName: "Nom Légal Complet",
    identification: "Identification (PPSN)",
    parentDependentMode: "Mode Enfant / Dépendant",
    sos: "SOS",
    safeWalk: "Marche Sécurisée",
    crimeMap: "Carte de la Criminalité",
    dvAlert: "Alerte Violence Domestique",
    medicalProfile: "Profil Médical",
    report: "Signaler",
    settings: "Paramètres",
    emergencyActivated: "URGENCE ACTIVÉE",
    gardaETA: "ETA de Garda",
    cancelSOS: 'Annuler SOS',
    liveStatus: 'ÉTAT EN DIRECT',
  },
  de: {
    welcome: "Willkommen bei SLÁN",
    tagline: "Irlands Fortschrittliches Sicherheitsnetz",
    platformTitle: "Irische Bürgersicherheitsplattform",
    welcomeSubtitle: "Willkommen im SLÁN-Netzwerk",
    register: "Registrieren",
    login: "Anmelden",
    gardaLogin: "Garda Login",
    govLogin: "Regierung Login",
    officialLogin: "OFFIZIELLER LOGIN",
    username: "Benutzername",
    password: "Passwort",
    createAccount: "Konto Erstellen",
    loginSubtitle: "Geben Sie Ihren Benutzernamen und Ihr Passwort ein oder nutzen Sie Biometrie.",
    loginWithBiometrics: "Login mit Biometrie",
    registerSubtitle: "Registrieren Sie Ihre Identität, um der irischen Bürgersicherheitsplattform beizutreten.",
    fullName: "Vollständiger Name",
    identification: "Identifikation (PPSN)",
    parentDependentMode: "Kinder- / Abhängigenmodus",
    sos: "SOS",
    safeWalk: "Sicherer Weg",
    crimeMap: "Kriminalitätskarte",
    dvAlert: "Warnung Häusliche Gewalt",
    medicalProfile: "Medizinisches Profil",
    report: "Bericht",
    settings: "Einstellungen",
    emergencyActivated: "NOTFALL AKTIVIERT",
    gardaETA: "Garda Ankunft",
    cancelSOS: 'SOS Abbrechen',
    liveStatus: 'LIVE-STATUS',
  },
  it: {
    welcome: "Benvenuti in SLÁN",
    tagline: "Rete di Sicurezza Avanzata Irlandese",
    platformTitle: "Piattaforma di Sicurezza Cittadina Irlandese",
    welcomeSubtitle: "Benvenuti nella Rete SLÁN",
    register: "Registrati",
    login: "Accedi",
    gardaLogin: "Accesso Garda",
    govLogin: "Accesso Governo",
    officialLogin: "ACCESSO UFFICIALE",
    username: "Nome utente",
    password: "Password",
    createAccount: "Crea Account",
    loginSubtitle: "Inserisci username e password o usa la biometria per accedere.",
    loginWithBiometrics: "Accedi con Biometria",
    registerSubtitle: "Registra la tua identità per unirti alla piattaforma irlandese per la sicurezza dei cittadini.",
    fullName: "Nome Legale Completo",
    identification: "Identificazione (PPSN)",
    parentDependentMode: "Modalità Bambino / Dipendente",
    sos: "SOS",
    safeWalk: "Camminata Sicura",
    crimeMap: "Mappa Crimine",
    dvAlert: "Allerta Violenza Domestica",
    medicalProfile: "Profilo Medico",
    report: "Segnala",
    settings: "Impostazioni",
    emergencyActivated: "EMERGENZA ATTIVATA",
    gardaETA: "Arrivo Garda",
    cancelSOS: 'Annulla SOS',
    liveStatus: 'STATO LIVE',
  },
  pt: {
    welcome: "Bem-vindo ao SLÁN",
    tagline: "Rede de Segurança Avançada da Irlanda",
    platformTitle: "Plataforma de Segurança do Cidadão Irlandês",
    welcomeSubtitle: "Bem-vindo à Rede SLÁN",
    register: "Registrar",
    login: "Conectar",
    gardaLogin: "Login Garda",
    govLogin: "Login Governo",
    officialLogin: "LOGIN OFICIAL",
    username: "Usuário",
    password: "Senha",
    createAccount: "Criar Conta",
    loginSubtitle: "Insira seu usuário e senha ou use biometria para entrar.",
    loginWithBiometrics: "Login com Biometria",
    registerSubtitle: "Registre sua identidade para participar da Plataforma de Segurança do Cidadão Irlandês.",
    fullName: "Nome Legal Completo",
    identification: "Identificação (PPSN)",
    parentDependentMode: "Modo Criança / Dependente",
    sos: "SOS",
    safeWalk: "Caminhada Segura",
    crimeMap: "Mapa de Crime",
    dvAlert: "Alerta de Violência Doméstica",
    medicalProfile: "Perfil Médico",
    report: "Relatar",
    settings: "Configurações",
    emergencyActivated: "EMERGÊNCIA ATIVADA",
    gardaETA: "Chegada da Garda",
    cancelSOS: 'Cancelar SOS',
    liveStatus: 'STATUS AO VIVO',
  },
  pl: {
    welcome: "Witaj w SLÁN",
    tagline: "Zaawansowana Sieć Bezpieczeństwa w Irlandii",
    platformTitle: "Irlandzka Platforma Bezpieczeństwa Obywateli",
    welcomeSubtitle: "Witaj w Sieci SLÁN",
    register: "Zarejestruj się",
    login: "Zaloguj się",
    gardaLogin: "Logowanie Garda",
    govLogin: "Logowanie Rządowe",
    officialLogin: "LOGOWANIE OFICJALNE",
    username: "Nazwa użytkownika",
    password: "Hasło",
    createAccount: "Utwórz konto",
    loginSubtitle: "Wprowadź nazwę użytkownika i hasło lub użyj biometrii.",
    loginWithBiometrics: "Zaloguj się biometrią",
    registerSubtitle: "Zarejestruj swoją tożsamość, aby dołączyć do irlandzkiej platformy bezpieczeństwa obywateli.",
    fullName: "Imię i nazwisko",
    identification: "Identyfikacja (PPSN)",
    parentDependentMode: "Tryb dziecka / podopiecznego",
    sos: "SOS",
    safeWalk: "Bezpieczny spacer",
    crimeMap: "Mapa przestępczości",
    dvAlert: "Alert o przemocy domowej",
    medicalProfile: "Profil medyczny",
    report: "Zgłoś",
    settings: "Ustawienia",
    emergencyActivated: "ALARM AKTYWOWANY",
    gardaETA: "Czas przybycia Gardy",
    cancelSOS: 'Anuluj SOS',
    liveStatus: 'STATUS NA ŻYWO',
  },
  ro: {
    welcome: "Bun venit la SLÁN",
    tagline: "Rețeaua Avansată de Siguranță din Irlanda",
    platformTitle: "Platforma de Siguranță a Cetățenilor Irlandezi",
    welcomeSubtitle: "Bun venit în Rețeaua SLÁN",
    register: "Înregistrare",
    login: "Autentificare",
    gardaLogin: "Autentificare Garda",
    govLogin: "Autentificare Guvern",
    officialLogin: "AUTENTIFICARE OFICIALĂ",
    username: "Utilizator",
    password: "Parolă",
    createAccount: "Creează cont",
    loginSubtitle: "Introdu utilizatorul și parola sau folosește biometria.",
    loginWithBiometrics: "Autentificare biometrică",
    registerSubtitle: "Înregistrează-ți identitatea pentru a te alătura platformei de siguranță a cetățenilor irlandezi.",
    fullName: "Nume complet legal",
    identification: "Identificare (PPSN)",
    parentDependentMode: "Mod copil / dependent",
    sos: "SOS",
    safeWalk: "Plimbare sigură",
    crimeMap: "Hartă infracționalitate",
    dvAlert: "Alertă violență domestică",
    medicalProfile: "Profil medical",
    report: "Raportează",
    settings: "Setări",
    emergencyActivated: "URGENȚĂ ACTIVATĂ",
    gardaETA: "Sosire Garda",
    cancelSOS: 'Anulează SOS',
    liveStatus: 'STARE LIVE',
  },
  nl: {
    welcome: "Welkom bij SLÁN",
    tagline: "Ierlands Geavanceerde Veiligheidsnetwerk",
    platformTitle: "Iers Burgerveiligheidsplatform",
    welcomeSubtitle: "Welkom bij het SLÁN-netwerk",
    register: "Registreren",
    login: "Inloggen",
    gardaLogin: "Garda Login",
    govLogin: "Overheid Login",
    officialLogin: "OFFICIËLE LOGIN",
    username: "Gebruikersnaam",
    password: "Wachtwoord",
    createAccount: "Account aanmaken",
    loginSubtitle: "Voer uw gebruikersnaam en wachtwoord in of gebruik biometrie.",
    loginWithBiometrics: "Inloggen met biometrie",
    registerSubtitle: "Registreer uw identiteit om lid te worden van het Ierse burgerveiligheidsplatform.",
    fullName: "Volledige wettelijke naam",
    identification: "Identificatie (PPSN)",
    parentDependentMode: "Kind / Afhankelijke modus",
    sos: "SOS",
    safeWalk: "Veilige wandeling",
    crimeMap: "Misdaadkaart",
    dvAlert: "Huiselijk geweld alert",
    medicalProfile: "Medisch profiel",
    report: "Meld",
    settings: "Instellingen",
    emergencyActivated: "NOODGEVAL GEACTIVEERD",
    gardaETA: "Aankomsttijd Garda",
    cancelSOS: 'SOS annuleren',
    liveStatus: 'LIVE STATUS',
  }
};
